[build]
  base = "socrates-landing"
  command = "npm run build"
  publish = "dist"

[build.environment]
  # These variables must also be set in the Netlify UI to be secure and effective
  NODE_VERSION = "20"
